manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    - name: benvallack
      url-base: https://github.com/benvallack
    - name: ftc
      url-base: https://github.com/ftc/
    - name: hypan599
      url-base: https://github.com/hypan599
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    # - name: zmk
    #   remote: urob
    #   revision: main
    #   import: app/west.yml
    - name: zmk-helpers
      remote: urob
      revision: main
  self:
    path: config
